name: Release
on:
  release:
    types: [released]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          nodetail: true
          title: New version of `kitachan.black` is released!
          description: |
            Version: `${{ env.RELEASE_VERSION }}`
            Title: ${{ github.event.release.name }}
            Link: [${{ github.event.release.html_url }}](${{ github.event.release.html_url }})
            Body
            ${{ github.event.release.body }}
